config/routes.rb
Wxapp::Application.routes.draw do
 
  resources :locations

  resources :users do
    member do
      get :following, :followers
    end
  end 
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :forecasts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  resources :galleries
  resources :pictographs do
    member { post :vote }
    member do
      get :image
    end
  end

  resources :forums
  resources :subforums
  resources :discussions
  resources :comments
  resources :piccomments
  resources :cities
  resources :stations
  
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/weatherate', to: 'static_pages#weatherate'

  match '/newgallery', to: 'galleries#create'
  match '/pics', to: 'galleries#index'
  match '/uploadpic', to: 'pictographs#new'

  match '/newforum', to: 'forums#new'
  match '/newsubforum', to: 'subforums#new'
  

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  attr_accessible :name, :opencomment, :subforum_id, :forum_id
  belongs_to :subforum
  belongs_to :user
  has_many :comments

  validates :user_id, presence: true
  validates :subforum_id, presence: true
  validates :name, presence: true, length: { maximum: 90, minimum: 3 }
  validates :opencomment, presence: true, length: { maximum: 2000 }

  default_scope order: 'discussions.updated_at DESC'
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  before_filter :admin_user,   only: :destroy
  
  def new
    @discussion = Discussion.new
  end

  def create
    @discussion = current_user.discussions.build(params[:discussion])
    if @discussion.save
      flash[:success] = "Thread created!"
      redirect_to @discussion
    else
      flash[:error] = "Something went awry!"
      redirect_to @discussion.subforum
    end
  end

  def show
    @discussion = Discussion.find(params[:id])
    @comment = @discussion.comments.build
    @comments = @discussion.comments.paginate(page: params[:page])
  end
  
  def destroy
    @discussion.destroy
    redirect_to forums_path
  end

  private

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end 
    
    def correct_user
      @discussion = current_user.discussions.find_by_id(params[:id])
      redirect_to root_path if @discussion.nil?
    end  
  
end



app/helpers/discussions_helper.rb
module DiscussionsHelper

  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

    def wrap_long_string(text, max_width = 75)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text : 
                                  text.scan(regex).join(zero_width_space)
    end
end



app/views/discussions/_comment_form.html.erb
<%= form_for(@comment) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <aside>
  <div class="field">
    <%= f.text_area :content, placeholder: "Add your comments..." %>
  </div>
  <div class="field">
    <%= f.hidden_field :discussion_id, value: @discussion.id %>
  </div>

  <%= f.submit "Add Comment", class: "btn btn-primary" %>
<% end %>
</aside>



app/views/discussions/_discussion.html.erb
<li>

  <span class="content"><%= link_to (discussion.name), discussion %></span>

</li>






app/views/discussions/show.html.erb
<h3 class="linkage"><%= link_to @discussion.subforum.forum.name, @discussion.subforum.forum %> > <%= link_to @discussion.subforum.name, @discussion.subforum %></h3></br>
<h3><%= @discussion.name %></h3>
<ul class="subforumlist opencom">
<div class="row">
  <div class="span2">
    <span class="user"><%= link_to @discussion.user.name, @discussion.user %></span>
    <span class="user"><%= link_to gravatar_for(@discussion.user), @discussion.user, size: 52 %></span>
  </div>
  <div class="span7">
    <span class="content"><%= sanitize @discussion.opencomment.gsub(/\n/,"</br>"), tags: %w(br img), attributes: %w(src) %></span>
    <span class="timestamp">
      <%= time_ago_in_words(@discussion.created_at) %> ago
    </span>
  </div>  
</div>
</ul>

<ol class="microposts">
  <%= render @comments %>
</ol>

<% if signed_in? %>
  <%= render 'comment_form' %>
<% else %>
  <strong>
    Please <%= link_to "sign in", signin_path %> to comment
  </strong>
<% end %>