config/routes.rb
Wxapp::Application.routes.draw do
 
  resources :locations

  resources :users do
    member do
      get :following, :followers
    end
  end 
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :forecasts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  resources :galleries
  resources :pictographs do
    member { post :vote }
    member do
      get :image
    end
  end

  resources :forums
  resources :subforums
  resources :discussions
  resources :comments
  resources :piccomments
  resources :cities
  resources :stations
  
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/weatherate', to: 'static_pages#weatherate'

  match '/newgallery', to: 'galleries#create'
  match '/pics', to: 'galleries#index'
  match '/uploadpic', to: 'pictographs#new'

  match '/newforum', to: 'forums#new'
  match '/newsubforum', to: 'subforums#new'
  

end

app/views/shared/_carousel.html.erb


<div id="myCarousel" class="carousel slide">
  <!-- Carousel items -->
  <center>
  <div class="carousel-inner">
    <div class="active item"><%= image_tag "mountains_fo_lyfe/038_2.JPG", size: "800x600" %></div>
    <div class="item"><%= image_tag "mountains_fo_lyfe/247.JPG", size: "800x600" %></div>
    <div class="item"><%= image_tag "mountains_fo_lyfe/150.JPG", size: "800x600" %></div>
    <div class="item"><%= image_tag "mountains_fo_lyfe/181.JPG", size: "800x600" %></div>
    <div class="item"><%= image_tag "mountains_fo_lyfe/166.JPG", size: "800x600" %></div>
    <div class="item"><%= image_tag "mountains_fo_lyfe/207.JPG", size: "800x600" %></div>
    <div class="item"><%= image_tag "mountains_fo_lyfe/356_1.jpg", size: "800x600" %></div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
</center>

<script>
  $('.carousel').carousel({
    interval: 5000
  })  
</script>


app/views/shared/_cityforecast.html.erb
<h1><em>Today</em> &emsp; <%= image_tag @icons[0] %> <%= @hi_temp[0].content %> &deg;F</h1>
<h1><em><%= Date::DAYNAMES[Date.today().tomorrow().wday()] %></em> &emsp; <%= image_tag @icons[2] %> <%= @hi_temp[1].content %> / <%= @lo_temp[0].content %></h1>
<h1><em><%= Date::DAYNAMES[Date.today().tomorrow().tomorrow().wday()] %></em> &emsp; <%= image_tag @icons[4] %> <%= @hi_temp[2].content %> / <%= @lo_temp[1].content %></h1>
<h1><em><%= Date::DAYNAMES[Date.today().tomorrow().tomorrow().tomorrow().wday()] %></em> &emsp; <%= image_tag @icons[6] %> <%= @hi_temp[3].content %> / <%= @lo_temp[2].content %></h1>
<h1><em><%= Date::DAYNAMES[Date.today().tomorrow().tomorrow().tomorrow().tomorrow().wday()] %></em> &emsp; <%= image_tag @icons[8] %> <%= @hi_temp[4].content %> / <%= @lo_temp[3].content %></h1>

app/views/shared/_currentwx.html.erb
<div class="hero-unit currentcond">
<div id="accordion2" class="accordion">
            <div class="accordion-group">
              <div class="accordion-heading">
                <a href="#collapseOne" data-parent="#accordion2" data-toggle="collapse" class="accordion-toggle">
                    <h1>
    <center>
      <em><%= @cityy %> &emsp;
      <%= image_tag @curconditionspic %></em>
      <%= @temperature %> &deg;F
    </center>
  </h1>
                </a>
              </div>
              <div class="accordion-body collapse" id="collapseOne" style="height: 0px;">
  	      <div class="accordion-inner">
                  <% if (@lo_temp.length == 6) %>
 		    <%= render 'shared/cityforecast' %>
                  <% else %>
		    <%= render 'shared/cityforecast1' %>
                  <% end %>
		  
                </div>
              </div>
            </div>
          </div>  

</div>

<script>
  $(".chzn-select").chosen();
</script>

<script>
$(function() {
    $('#accordion2').on('mouseenter.collapse.data-api', '[data-toggle=collapse]', function(e) {
        var $this = $(this),
            href, target = $this.attr('data-target') || e.preventDefault() || (href = $this.attr('href')) && href.replace(/.*(?=#[^\s]+$)/, '') //strip for ie7
            ,
            option = $(target).data('collapse') ? 'show' : $this.data()
            $(target).collapse(option)
    })
    $('#accordion2').on('mouseleave.collapse.data-api', '[data-toggle=collapse]', function(e) {
        var $this = $(this),
            href, target = $this.attr('data-target') || e.preventDefault() || (href = $this.attr('href')) && href.replace(/.*(?=#[^\s]+$)/, '') //strip for ie7
            ,
            option = $(target).data('collapse') ? 'hide' : $this.data()
            $(target).collapse(option)
    })
    
})
</script>	

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>


app/views/shared/_feed_item.html.erb
<ul class="subforumlist opencom hihi" id="<%= feed_item.id %>">
  <div class="row">
    <div class="span2">
      <span class="user">
        <%= link_to feed_item.user.name, feed_item.user, class: "shitfucker", title: feed_item.user.name, "data-content" => (pluralize(feed_item.user.microposts.count, "Post")+" | "+pluralize(feed_item.user.forecasts.count, "Forecast")+" | "+pluralize(feed_item.user.followers.count, "Follower")+" | Following "+feed_item.user.followed_users.count.to_s)%>
      </span>
      <span class="user"><%= link_to gravatar_for(feed_item.user), feed_item.user %></span>
    </div>
    <div class="span3">
      <span class="content"><%= h(feed_item.content) %></span>
      <span class="timestamp">
        <%= time_ago_in_words(feed_item.created_at) %> ago
      </span>
      <% if current_user?(feed_item.user) %>
        <%= link_to "delete", feed_item, method: :delete,
                                         data: { confirm: "You sure?" },
                                         title: feed_item.content %>	
      <% end %>
    </div>
  </div>
</ul>

<script>
  $('.shitfucker').popover({ html : true });
</script>

app/views/shared/_ffeed.html.erb
<% if @ffeed_items.any? %>
  <ol class="forecasts">
    <%= render partial: 'shared/ffeed_item', collection: @ffeed_items %>
  </ol>
  <%= will_paginate @ffeed_items %>
<% else %>
  </br><h5>No items to display</h5>
<% end %>



app/views/shared/_forecast_form.html.erb
<%= form_for(@forecast) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field"> 
    <h3>Create a Forecast</h3>	  
    <%= f.label "Conditions" %>
    <%= f.select :sensible, [["Sunny", "Sunny"], ["Snow", "Snow"], ["Rain", "Rain"], ["Cloudy", "Cloudy"]], {prompt: "-Select Conditions-"}, { class: "chzn-select" } %>

    <%= f.label "High Temp." %>
    <%= f.text_field :hi_temp, placeholder: "High Temperature (F)" %>

    <%= f.label "Low Temp." %>
    <%= f.text_field :lo_temp, placeholder: "Low Temperature (F)" %>

    <%= f.label "Wind Speed" %>
    <%= f.text_field :ws, placeholder: "Wind Speed (mph)" %>

    <%= f.label "wind direction" %>
    <%= f.select :wd, [["N", 0], ["NE", 45], ["E", 90], ["SE", 135], ["S", 180], ["SW", 225], ["W", 270], ["NW", 315]] %>

    <%= f.label "Chance of Precipitation" %>
    <%= f.select :precip_chance, [["0 %", 0], ["10 %", 10], ["20 %", 20], ["30 %", 30], ["40 %", 40], ["50 %", 50], ["60 %", 60], ["70 %", 70], ["80 %", 80], ["90 %", 90], ["100 %", 100]] %>

    <%= f.label "Precipitation Amount" %>
    <%= f.select :qpf, [["0.00\" or trace", 0], ["0.01\" - 0.24\"", 1], ["0.25\" - 0.49\"", 2], ["0.50\" - 0.74\"", 3], ["0.75\" - 0.99\"", 4], ["1.00\" - 1.50\"", 5], ["1.50\" - 1.99\"", 6], ["2.00\" +", 7]] %>
  </div>
  <%= f.submit "Submit Forecast", class: "btn btn-large btn-primary" %>
<% end %>

<script>
  $(".chzn-select").chosen();
</script>

app/views/shared/_gallery_form.html.erb
<%= form_for(@gallery) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :name, placeholder: "Gallery Name" %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>


app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <h3>Post About the Weather</h3>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>


app/views/shared/_pictograph_form.html.erb
</br>
<aside>
  <div class="row">
    <div class="span5">
      <div class="span4 offset1">
        <%= form_for(@pictograph, html: { multipart: true } ) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <div class="field">
            <%= f.label "Title" %>
            <%= f.text_field :name, placeholder: "Picture Title" %>
          </div>
          <div class="field">
            <%= f.label "Description" %>
            <%= f.text_area :description, placeholder: "Enter picture description here!" %>
          </div>
          <div>
            <%= f.label "Select a Gallery" %>
            <%= f.select :gallery_id, [["Sunset/Sunrise", 1], ["Clouds", 2], ["Snow", 3], ["Rain", 4]] %>
          </div>
          <div>
            <%= f.label "Choose picture file" %>
            <%= f.file_field :image %>
          </div>
          <%= f.submit "Post", class: "btn btn-large btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</aside>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>


app/views/shared/_subforum_form.html.erb
</br>
<aside>
  <div class="row">
    <div class="span5">
      <div class="span4 offset1">
        <%= form_for(@subforum, html: { multipart: true } ) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <div class="field">
            <%= f.label "Name" %>
            <%= f.text_field :name, placeholder: "Subforum Name" %>
          </div>
          <div>
            <%= f.label "Select a Parent Forum" %>
            <%= f.select :forum_id, [["Main Forums", 1], ["Regional Forums", 2], ["Event Forums", 3]] %>
          </div>
          <%= f.submit "Create Subforum", class: "btn btn-large btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</aside>


app/views/shared/_toptab.html.erb
<ul class="nav nav-tabs" id="myTab">
  <li><a href="#posts">Posts</a></li>
  <li><a href="#forecasts">Forecasts</a></li>
  <li><a href="#pictures">Pictures</a></li>
  <li><a href="#videos">Videos</a></li>
</ul>
 
<div class="tab-content">
  <div class="tab-pane" id="posts">
    <h3>Weather Feed</h3>
    <%= render 'shared/feed' %>
  </div>
  <div class="tab-pane" id="forecasts">
    <h3>Forecasts</h3>
    <%= render 'shared/ffeed' %>
  </div>
  <div class="tab-pane" id="pictures">...</div>
  <div class="tab-pane" id="videos">
    <h3>Forecasts</h3>
    <%= render 'shared/ffeed' %>
  </div>
</div>
 
<script>
  
  $('#myTab a').click(function (e) {
    e.preventDefault();
    $(this).tab('show');
  })

  $(function() { 
    $('a[data-toggle="tab"]').on('shown', function (e) {
      //save the latest tab; use cookies if you like 'em better:
      localStorage.setItem('lastTab', $(e.target).attr('id'));
    });

    //go to the latest tab, if it exists:
    var lastTab = localStorage.getItem('lastTab');
    if (lastTab) {
      $('#'+ lastTab).tab('show');
    } else {
      $('#myTab a:first').tab('show');
    }
  });
  

</script>


app/views/shared/_user_infoo.html.erb
<a href="<%= user_path(@user) %>">
  <%= gravatar_for @user, size: 52 %>
  <h1>
  <%= @user.name %>
  </h1>
</a>

<span>
  <%= pluralize(@user.microposts.count, "Post") %> | 
  <%= pluralize(@user.forecasts.count, "Forecast") %>
</span>

